### ISSUE TITLE
Huge Memory consumption 

### ISSUE THREAD

**Issue by Colorstorm** [MHH-RCUG/Heatmaps#3]
Hi, 

I have tried to run some test and had a lot of trouble with the huge amount of memory that is needed.

@konnosif which settings do you use?

Maybe we could think about making the settings with the least memory usage default and add a comment that other settings take a lot of memory

**Comment by colindaven** [comment]
Konstantinos' working command:

command i used on Ubuntu * ubuntu on windows 10..! on a 8 GB deskop on toy dataset (Github) :

`python3 heat5.py --batch_files sample.txt --filter_sTF 1 --filter_sStart 0 --filter_sEnd 4 -- suffix_label A --genus 1 --corr 0`

**Comment by colindaven** [comment]
Huge RAM use was due to the coverage window, and not the bam.txt files, being used as input.
